version: "3.8"

services:

  mongo:
    image: mongo
    container_name: ids_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: ids_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ids

  frontend:
    build: ./frontend
    container_name: ids_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  mongo_data:
  jenkins_home: